site_name: Pydoll Documentation
theme:
  name: material
plugins:
  - mkdocstrings:
      default_handler: python
nav:
  - Home: index.md
  - API:
      - Overview: api/overview.md
      - Browser: api/browser.md
      - Commands: api/commands.md
